### ISSUE TITLE
allow sudo or run as USER root

### ISSUE THREAD

**Issue by eighthave** [mpl/go4droid#4]
Thanks for this very useful Docker image!  I need to add some dependencies on top of this image for some projects, but it runs as `USER gopher`, so it can't install packages.   This image could either be switched to run as _root_, or include _sudo_ with the _gopher_ user having sudo access.

**Comment by mpl** [comment]
thanks, I didn't think it would be useful for anyone else. Adding sudo SGTM. You wanna send a PR for it?

**Comment by mpl** [comment]
PTAL: https://github.com/mpl/go4droid/pull/5

**Comment by eighthave** [comment]
works for me

**Comment by eighthave** [comment]
FYI, I ended up needing to make my own Docker image for this.  Here's mine for anyone who wants a Docker image designed around the GitLab CI use case:
https://gitlab.com/eighthave/ci-image-gomobile/container_registry

It is used like this:

```yaml
android:
  image: registry.gitlab.com/eighthave/ci-image-gomobile
  script:
    - export src=$GOPATH/src
    - mkdir -p $src/git.torproject.org/pluggable-transports
    - mkdir -p $src/github.com/keroserene
    - mkdir -p $src/gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR $src/git.torproject.org/pluggable-transports/snowflake
    - ln -s $CI_PROJECT_DIR $src/git.torproject.org/pluggable-transports/snowflake.git
    - ln -s $CI_PROJECT_DIR $src/github.com/keroserene/snowflake
    - ln -s $CI_PROJECT_DIR $src/github.com/keroserene/snowflake.git
    - ln -s $CI_PROJECT_DIR $src/gitlab.com/$CI_PROJECT_PATH
    - ln -s $CI_PROJECT_DIR $src/gitlab.com/${CI_PROJECT_PATH}.git

    - cd $src/github.com/keroserene/snowflake/client
    - git checkout -B $CI_COMMIT_REF_NAME origin/$CI_COMMIT_REF_NAME # force to a branch for `go get -u`
    - go get -d -u ./...
    - git -C $src/github.com/keroserene/go-webrtc fetch https://gitlab.com/eighthave/go-webrtc.git
    - git -C $src/github.com/keroserene/go-webrtc reset --hard FETCH_HEAD
    - cp $src/github.com/keroserene/go-webrtc/webrtc-android-armeabi-v7a.pc
         $src/github.com/keroserene/go-webrtc/webrtc-linux-arm.pc  # cgo uses both on Android :-/
    - export CGO_CXXFLAGS=-D_GLIBCXX_USE_CXX_ABI=1
    - export CGO_CFLAGS="-fsanitize=address"
    - export CGO_LDFLAGS="-fsanitize=address"
    - gomobile bind -v -x -target=android github.com/keroserene/snowflake/client

```
